from django.urls import path

from .views import (
    AccountDeactivateView,
    AvatarUploadView,
    CustomTokenObtainPairView,
    CustomTokenRefreshView,
    EmailChangeConfirmView,
    EmailChangeRequestView,
    DeviceDetailView,
    DeviceListView,
    DeviceRevokeAllView,
    LogoutView,
    MeView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PatientProfileView,
    RegisterView,
    SocialLoginView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='auth-register'),
    path('login/', CustomTokenObtainPairView.as_view(), name='auth-login'),
    path('social/<str:provider>/', SocialLoginView.as_view(), name='auth-social-login'),
    path('token/refresh/', CustomTokenRefreshView.as_view(), name='auth-token-refresh'),
    path('logout/', LogoutView.as_view(), name='auth-logout'),
    path('devices/', DeviceListView.as_view(), name='auth-devices'),
    path('devices/revoke-all/', DeviceRevokeAllView.as_view(), name='auth-devices-revoke-all'),
    path('devices/<int:pk>/', DeviceDetailView.as_view(), name='auth-device-detail'),
    path('me/', MeView.as_view(), name='auth-me'),
    path('deactivate/', AccountDeactivateView.as_view(), name='auth-deactivate'),
    path('email/change/', EmailChangeRequestView.as_view(), name='auth-email-change'),
    path('email/change/confirm/', EmailChangeConfirmView.as_view(), name='auth-email-change-confirm'),
    path('profile/avatar/', AvatarUploadView.as_view(), name='auth-avatar-upload'),
    path('profile/patient/', PatientProfileView.as_view(), name='auth-patient-profile'),
    path('password/change/', PasswordChangeView.as_view(), name='auth-password-change'),
    path('password/reset/', PasswordResetRequestView.as_view(), name='auth-password-reset'),
    path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='auth-password-reset-confirm'),
]
