# Generated by Django 6.0.6 on 2026-07-28 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, choices=[('', 'None'), ('basic', 'Başlanğıc'), ('pro', 'Peşəkar')], default='', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_stage', models.CharField(blank=True, choices=[('', 'None'), ('t-3', 'T-3 days'), ('t-1', 'T-1 day'), ('t-0', 'T-0')], default='', max_length=5)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('', 'None'), ('basic', 'Başlanğıc'), ('pro', 'Peşəkar')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='AZN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('provider', models.CharField(default='payriff', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('provider_session_id', models.CharField(blank=True, max_length=255)),
                ('payment_url', models.URLField(blank=True, max_length=500)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='subscriptions.doctorsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_order_id', ''), _negated=True), fields=('provider_order_id',), name='subscriptionpayment_unique_provider_order_id')],
            },
        ),
    ]
