# Generated by Django 6.0.6 on 2026-07-28 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_dependent'),
        ('family', '0001_initial'),
        ('payments', '0002_payment_dependent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_order_id', ''), _negated=True), fields=('provider_order_id',), name='payment_unique_provider_order_id'),
        ),
    ]
