# Generated by Django 6.0.6 on 2026-06-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('gynecology', 'Gynecology'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('oncology', 'Oncology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine')], default='general_practice', max_length=50),
        ),
    ]
