# Generated by Django 6.0.6 on 2026-06-22 20:46

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='diploma_file',
            field=models.FileField(blank=True, null=True, storage=apps.users.models.diploma_storage, upload_to='diplomas/'),
        ),
    ]
