# Generated by Django 6.0.6 on 2026-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctorprofile_diploma_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'used', 'expires_at'], name='users_passw_user_id_2ad8ef_idx'),
        ),
    ]
