# Generated by Django 6.0.6 on 2026-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctorprofile_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='cancellation_window_hours',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
