# Generated by Django 6.0.6 on 2026-07-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_doctorprofile_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
