# Generated by Django 6.0.6 on 2026-07-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_emailchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('az', 'Azerbaijani'), ('tr', 'Turkish'), ('fr', 'French'), ('zh', 'Chinese')], default='en', max_length=5),
        ),
    ]
