# Generated by Django 6.0.6 on 2026-07-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('gynecology', 'Gynecology'), ('urology', 'Urology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose & Throat)'), ('oncology', 'Oncology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine')], db_index=True, default='general_practice', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], db_index=True, max_length=10),
        ),
    ]
