# Generated by Django 6.0.6 on 2026-07-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_doctorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='previous_jti',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
