# Generated by Django 6.0.6 on 2026-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userdevice_previous_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
