# Generated by Django 6.0.6 on 2026-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_patientprofile_city_patientprofile_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('hospital', 'Hospital')], db_index=True, max_length=10),
        ),
    ]
