# Generated by Django 6.0.6 on 2026-07-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
