# Generated by Django 6.0.6 on 2026-07-26 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_conversation_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggers', models.JSONField(default=dict)),
                ('answers', models.JSONField(default=dict)),
                ('specialization', models.CharField(blank=True, choices=[('general_practice', 'general_practice'), ('cardiology', 'cardiology'), ('dermatology', 'dermatology'), ('neurology', 'neurology'), ('orthopedics', 'orthopedics'), ('pediatrics', 'pediatrics'), ('psychiatry', 'psychiatry'), ('gynecology', 'gynecology'), ('urology', 'urology'), ('ophthalmology', 'ophthalmology'), ('ent', 'ent'), ('oncology', 'oncology'), ('endocrinology', 'endocrinology'), ('gastroenterology', 'gastroenterology'), ('pulmonology', 'pulmonology'), ('radiology', 'radiology'), ('anesthesiology', 'anesthesiology'), ('emergency_medicine', 'emergency_medicine')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
