# Generated by Django 6.0.6 on 2026-07-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_responsetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='summary_generated_at',
        ),
    ]
