# Generated by Django 6.0.6 on 2026-07-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('medications', '0002_medication_prescription_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_medications', to='family.dependent'),
        ),
    ]
