# Generated by Django 6.0.6 on 2026-07-23 04:45

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_workplace_latitude_workplace_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops (used by the index below) needs the pg_trgm extension.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='workplace',
            index=django.contrib.postgres.indexes.GinIndex(fields=['city'], name='workplace_city_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
