# Generated by Django 6.0.6 on 2026-07-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_workplace_workplace_city_trgm_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workplace',
            name='workplace_city_trgm_idx',
        ),
        migrations.AddField(
            model_name='workplace',
            name='region',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
