# Generated by Django 6.0.6 on 2026-07-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_workplace_city'),
        ('hospitals', '0002_hospitaldoctorlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplaces', to='hospitals.hospital'),
        ),
    ]
