# Generated by Django 6.0.6 on 2026-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('requires_rescheduling', 'Requires Rescheduling'), ('no_show', 'No-show')], default='pending', max_length=30),
        ),
    ]
