# Generated by Django 6.0.6 on 2026-07-02 18:55

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_appt_status_ends_idx'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The exclusion constraint needs GiST support for scalar equality on
        # doctor_id combined with range overlap.
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['cancelled', 'declined']), _negated=True), expressions=[('doctor', '='), (models.Func(models.F('starts_at'), models.F('ends_at'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='appt_no_overlap_per_doctor'),
        ),
    ]
