# Generated by Django 6.0.6 on 2026-07-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_review_updated_at'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dependent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='family.dependent'),
        ),
    ]
