# Generated by Django 6.0.6 on 2026-08-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_dependent'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
    ]
