# Generated by Django 6.0.6 on 2026-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_review_needs_manual_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_cancelled_late',
            field=models.BooleanField(default=False),
        ),
    ]
