# Generated by Django 6.0.6 on 2026-07-28 14:06

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops (used by the GinIndex below) needs the pg_trgm
        # extension. CREATE EXTENSION IF NOT EXISTS is idempotent, so this
        # is safe even though apps.doctors' 0003 migration also creates it
        # — Django gives no ordering guarantee between independent apps'
        # migrations, so this app must not assume that one has already run.
        TrigramExtension(),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=220)),
                ('city', models.CharField(choices=[('baku', 'Baku'), ('absheron', 'Absheron'), ('khizi', 'Khizi'), ('sumgait', 'Sumgait'), ('dashkasan', 'Dashkasan'), ('goranboy', 'Goranboy'), ('goygol', 'Goygol'), ('samukh', 'Samukh'), ('ganja', 'Ganja'), ('naftalan', 'Naftalan'), ('balakan', 'Balakan'), ('zaqatala', 'Zaqatala'), ('qakh', 'Qakh'), ('oghuz', 'Oghuz'), ('qabala', 'Qabala'), ('shaki', 'Shaki'), ('astara', 'Astara'), ('jalilabad', 'Jalilabad'), ('lerik', 'Lerik'), ('masally', 'Masally'), ('yardimli', 'Yardimli'), ('lankaran', 'Lankaran'), ('shabran', 'Shabran'), ('khachmaz', 'Khachmaz'), ('quba', 'Quba'), ('qusar', 'Qusar'), ('siyazan', 'Siyazan'), ('agdash', 'Agdash'), ('goychay', 'Goychay'), ('kurdamir', 'Kurdamir'), ('ujar', 'Ujar'), ('zardab', 'Zardab'), ('yevlakh', 'Yevlakh'), ('mingachevir', 'Mingachevir'), ('aghjabadi', 'Aghjabadi'), ('aghdam', 'Aghdam'), ('aghdara', 'Aghdara'), ('barda', 'Barda'), ('fuzuli', 'Fuzuli'), ('khojaly', 'Khojaly'), ('khojavend', 'Khojavend'), ('shusha', 'Shusha'), ('tartar', 'Tartar'), ('khankendi', 'Khankendi'), ('kalbajar', 'Kalbajar'), ('lachin', 'Lachin'), ('qubadli', 'Qubadli'), ('zangilan', 'Zangilan'), ('jabrayil', 'Jabrayil'), ('agsu', 'Agsu'), ('ismayilli', 'Ismayilli'), ('gobustan', 'Gobustan'), ('shamakhi', 'Shamakhi'), ('babek', 'Babek'), ('julfa', 'Julfa'), ('kangarli', 'Kangarli'), ('ordubad', 'Ordubad'), ('sadarak', 'Sadarak'), ('shahbuz', 'Shahbuz'), ('sharur', 'Sharur'), ('nakhchivan_city', 'Nakhchivan'), ('aghstafa', 'Aghstafa'), ('gadabay', 'Gadabay'), ('qazakh', 'Qazakh'), ('shamkir', 'Shamkir'), ('tovuz', 'Tovuz'), ('beylagan', 'Beylagan'), ('imishli', 'Imishli'), ('saatly', 'Saatly'), ('sabirabad', 'Sabirabad'), ('bilasuvar', 'Bilasuvar'), ('hajigabul', 'Hajigabul'), ('neftchala', 'Neftchala'), ('salyan', 'Salyan'), ('shirvan', 'Shirvan')], db_index=True, max_length=64)),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('confirmed', 'Confirmed'), ('merged', 'Merged'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=20)),
                ('claim_status', models.CharField(choices=[('none', 'No claim'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='none', max_length=20)),
                ('claim_requested_at', models.DateTimeField(blank=True, null=True)),
                ('claim_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_created', to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='hospitals.hospital')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='hospital_name_trgm_idx', opclasses=['gin_trgm_ops'])],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'merged'), _negated=True), fields=('normalized_name', 'city'), name='hospital_unique_normalized_name_per_city')],
            },
        ),
    ]
