# Generated by Django 6.0.6 on 2026-07-28 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDoctorLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('removed', 'Removed')], db_index=True, default='pending', max_length=10)),
                ('requested_by', models.CharField(choices=[('doctor', 'Doctor'), ('hospital', 'Hospital')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_links', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_links', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='hospitals_h_hospita_87af33_idx')],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'doctor'), name='hospital_doctor_link_unique')],
            },
        ),
    ]
