# Generated by Django 6.0.6 on 2026-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('rescheduling_required', 'Rescheduling Required'), ('general', 'General'), ('subscription', 'Subscription')], default='general', max_length=50),
        ),
    ]
